version: '2'

services:
    db:
        image: postgres:alpine
        volumes:
            - "pgdata:/var/lib/postgresql/data"
        environment:
            POSTGRES_DATABASE: mydb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: userpass
        ports:
            - 5432:5432
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE:  Berlin
        volumes:
            - ../wpe/:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        ports:
            - 9000:9000
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
volumes:
       pgdata:
