version: '3'

services:
    db:
        image: postgres:alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
    web:
        image: php:8.1-apache
        depends_on:
            - db
        build:
            context: php8-apache
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        ports:
            - 8080:80
volumes:
    pgdata:
